#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr -s 5120x1440

polybar example -r --config=$HOME/.config/polybar/config.ini &
picom -CGb &

feh --bg-fill $HOME/Pictures/evening-sky.png

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#96CDFB"
bspc config normal_border_color         "#6E6C7E"
bspc config active_border_color         "#6E6C7E"

xsetroot -cursor_name left_ptr
